services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis
    networks:
      - erp_network
    healthcheck:
      test:
        ['CMD', 'curl', '-f', 'http://api:${PORT}/api/v1/health-check/health']
      interval: 5m
      timeout: 30s
      retries: 5
      start_period: 20s

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - erp_network
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      --requirepass ${REDIS_PASSWORD}
    networks:
      - erp_network
    healthcheck:
      test:
        [
          'CMD',
          'redis-cli',
          '-h',
          'localhost',
          '-a',
          '${REDIS_PASSWORD}',
          'PING',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - erp_network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${S3_USER}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - storage-minio:/data
      - minio_data:/data
      - minio_config:/root/.minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - erp_network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

networks:
  erp_network:
    driver: bridge

volumes:
  # postgres data
  postgres_data:
  # minio data
  storage-minio:
    external: true
  minio_data:
  minio_config:
